export const TIME = {
    FETCH_DATETIME: "FETCH_DATETIME",
    FETCH_DATETIME_PENDING: "FETCH_DATETIME_PENDING",
    FETCH_DATETIME_REJECTED: "FETCH_DATETIME_REJECTED",
    FETCH_DATETIME_FULFILLED: "FETCH_DATETIME_FULFILLED",
    UPDATE_DATETIME: "UPDATE_DATETIME"
}

export const LANG = {
    SET_LANGUAGE: "SET_LANGUAGE",
}

export const COMMON = {
    CHANGE_MENU: "CHANGE_MENU",
    TOGGLE_OVERLAY: "TOGGLE_OVERLAY",
}