export const TIME = {
    FETCH_DATETIME: "FETCH_DATETIME",
    FETCH_DATETIME_REJECTED: "FETCH_DATETIME_REJECTED",
    FETCH_DATETIME_FULFILLED: "FETCH_DATETIME_FULFILLED",
    UPDATE_DATETIME: "UPDATE_DATETIME"
}